quotes = [ ' Le coup le plus rusé que le diable ait jamais réussi, c’est de faire croire à tout le monde qu’il n’existait pas. ',
          'J\'ai les mains faites pour l’or, et elles sont dans la merde ! ',
          'c\'est le nom de ta dernière SEXTAPE ?',
          'J\'ai dégusté son foie avec des fèves au beurre et un excellent Chianti ',
          ' Tu vois, le monde se divise en deux catégories: ceux qui ont un pistolet chargé et ceux qui creusent. Toi tu creuses',
          ' La vérité c\'est comme une couverture trop petite. Tu peux tirer dessus de tous les côtés, tu auras toujours les pieds froids. ',
          ' Les cons ça ose tout. C’est même à ça qu\'on les reconnait ',
          'Un grand pouvoir implique de grandes responsabilités. ',
          'T\'énerves pas p\'tit gars prends ta pelle et ton seau et va jouer !',
          'Le lion ne s\'associe pas avec le cafard!',
          'Tu vas avoir droit à dix petites secondes ! Pour déplacer ton gros cul dégueulasse ! Hors de chez moi ou je te plombe les boyaux avec du calibre 12! 1.2...10!',
          'Tu veux dire que ta présence ici est aussi utile qu\'un trou du cul à cet endroit là?',
          '-Monsieur Orange! Et Monsieur Pink ! -Pourquoi Monsieur Pink? - Parce que t\'es une pédale Ok',
          'Si vous le voulez bien, on se taillera des pipes plus tard, les enfants.',
          'Ils nous pissent dessus sans même essayer de nous faire croire qu\'il pleut !',
          'Je mets les pieds où je veux, Little John...et c\'est souvent dans la gueule',
          'Oh oui ! Tu la sens ma grosse intelligence !',
          'Les cons ça ose tout. C’est même à ça qu’on les reconnaît.',
          'Au cas où on se reverrait pas d\'ici là, une bonne soirée et une excellente nuit !',
          'Oh, c’est bon, y’a pas de quoi vermifuger un abribus...',
          'Petit tu es doué, très doué ; Mais tant que je serais dans le métier tu ne seras jamais que le second !',
          'S\'entrainer est inutile ! Seule compte la volonté !',
          'Ne me raconte plus que tu es innocent parce que c’est une insulte à mon intelligence et ça me rend de mauvaise humeur.',
          'Yippee-ki-yay, pauvre con !',
          'Félicitations tu vas bientôt toucher le fond, c’est bien.',
          'T\'aimes les omelettes, tiens j\'te casse les oeufs !',
          'La dernière fois que je l’ai vue, elle était dans une cage d’ascenseur avec un 4x4 planté dans le cul.',
          'C\'est aussi agréable que de se foutre une pomme de pin dans le cul !',
          'Moi je fais dans le sonore et le dégueulasse ! C’est mon style.',
          'Je me sens comme un paralytique qui doit effectuer une opération du cerveau avec une clé de 12.',
          'L’enfer c’est de se lever tous les matins et te demander pourquoi t’es là !',
          'Hartigan avait raison, si je crie pas chéri, tu peux pas bander. T’es qu’un pauvre naze !',
          'J’ai n’ai rien contre les négros, ritales, yuppins ou métèques. Ici vous n’êtes tous que des vrais connards.',
          'Miiiaaaouh ! On dirait que ça sent la chienne !',
          'Tu as de la chance, généralement ça ne va pas à tout le monde, la barbe. Mais toi, ça te fait une tête de dessous de bras',
          'Ça serait dommage de faire tuer 20 personnes juste pour prouver que t\'as un cerveau !',
          'Dites je peux vous poser une question? Comment vous avez fait pour pas être réformé à la visite médicale vous avez envoyé un singe à votre place ?',
          'Merci beaucoup, tronche de merde, casse-couilles, putain de saloperie d’enculé de machine à la mords-moi-le-nœud !',
          'Tu frappes comme un végétarien !',
          'Écoute bien ce que je dis : Tu vas fermer ta gueule, ou je te l’éclate sur le comptoir et je te fais bouffer tes dents !',
          'Dis donc on t’a jamais appris à manger avec la bouche fermée toi. C’est à toi que je cause. J’ai l’impression d’être à côté d’un camion poubelle qui travaille, moi ici !',
          'Si un jour je veux une amie comme vous, je m\'accroupirai et j\'en chierai une',
          'Comme tu voudras my ass licking cock sucker mother fucking son of a bitch !',
          'Ce n’est pas moi qui suis enfermé avec vous, mais vous qui êtes enfermés avec moi !',
          'Si t\'es pas joli sois au moins poli !',
          'T’as pas peur d’avoir les couilles explosées à chaque fois que tu t’assois ?',
          'N’oubliez pas que je suis à moitié humain. Ce qui fait que je suis à moitié stupide. Alors que vous, vous l’êtes à 100%.',
          'D\'ailleurs, ne dit-on pas qu\'une femme qui éclabousse un homme, c\'est un peu comme la rosée d\'une matinée de printemps, c\'est la promesse d\'une belle journée et la perspective d\'une soirée enflammée ?',
          'Pas de violence, c\'est les vacances !',
          'Eh bien monsieur l’expert en linguistique, « peace » est un terme qui peut être aussi utilisé en temps qu’interjection, salut, ou fin d’phrases, donc essaies de trouver un autre moyen de passer pour un con, ce que d’ailleurs entre nous, tu réussis à merveille. Peace.',
          'Pure pelouse… méga touz’ !',
          'Choppe le !',
          'Toi t’arrête de faire chier avec ton numéro de tapette, ton collier de burne et ta chemise de plouc! J’suis forcé de voir ta gueule et j’en fais pas un drame.',
          'Si j’ai réussi à redoubler 6 fois de suite la terminale de mon lycée, je suis sur que j’arriverai à squatter 12 ans dans ce repère de bourgeois.',
          'Parfait ! D’habitude j’me lève a 4h ça m’fra une grasse matinée !',
          'Oh une mini-pute !',
          '- Voilà qui explique tout… - Mais tu vois, ça guérit pas la connerie. Tu peux en fumer, tu resteras toujours un bouffon.',
          'Nous on t’a juste demandé de nous indiquer l’chemin. Main’nant j’crois que si on aurait demandé si quelqu’un aurait besoin d’une claque dans la gueule tu te serais écrasé comme une merde. Hein du con !' ]


